### ISSUE TITLE
[Search by Text] Enlarge the query text

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/MatchItFast#18]
The query text font is too small for presentation use. Please make it 200% larger.

**Comment by nagachika** [comment]
I have addressed your request. The updated version has been deployed to the staging demo site. Kindly confirm if it meets your expectations.

**Comment by kazunori279** [comment]
Thanks! Can you make the text area larger? It would be great if the area can show 2 - 3 lines and wide enough to cover 80% of the window width?

**Comment by nagachika** [comment]
Thank you for your confirmation. I understand your requests.

**Comment by nagachika** [comment]
@kazunori279 I have enlarged the text area and deployed it to the staging site. Please let me know if you have any other requests.

**Comment by kazunori279** [comment]
Looks perfect! Thanks!
