### ISSUE TITLE
Removing the latency numbers

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/MatchItFast#4]
Matching Engine is capable of providing better latency as short as 10ms or lower,  where as the current demo shows 60 - 80 ms. I suppose the current index is not adequately tuned for this specific use case. For the purpose of the demo as a generic technology introduction, please remove the latency numbers from the UI.

**Comment by nagachika** [comment]
In fact the latency measured on the GCE instance in the same VPC network tend to be around 10ms for image search. I think the major reason why the latency from App Engine was longer is that the request should be routed via VPC Serverless Access connector.

Anyway, I will remove the latency labels in the query results.
