### ISSUE TITLE
Remove duplication from the document search results

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/MatchItFast#6]
We see some results are duplicated.

**Comment by nagachika** [comment]
The document entries are de-duplicated based on the hash function of the (title +  url).

I think the titles could be duplicated on the results.
But if you deduplicate the entries based on title only, the number of articles is reduced to about 2.7 million.

```
SELECT 
COUNT(distinct title) as unique_title_count,
COUNT(distinct CONCAT(title, "|", url)) as unique_title_and_url_count
FROM `...`
```

```
Row | unique_title_count | unique_title_and_url_count
-- | -- | --
1 | 2708031 | 3709742
```

Maybe some sites assigned the same titles for all of the pages...

**Comment by kazunori279** [comment]
I feel it's more important to show the divergence (but all related to the original topic) on the results to show the power of the vector search. 2.7 million still looks impressive.

**Comment by nagachika** [comment]
I see. I will reconstruct the index of the articles from the GDELT public dataset with unique title constraints.

**Comment by kazunori279** [comment]
Thanks so much!!

**Comment by nagachika** [comment]
Updated the Matching Engine index with unique title articles.
@kazunori279 Would you please check the query results again?

**Comment by kazunori279** [comment]
Looks awesome! Thanks!
