### ISSUE TITLE
First queries takes longer time

### ISSUE THREAD

**Issue by kazunori279** [groovenauts/MatchItFast#7]
When I tried the document search, it took over 5 seconds to get the result. I suppose this is due to the client-side encoding of the text to an embedding. So, one idea is to let users press the button two times: the button label would change from 1) "Create a query vector" to 2) "Execute a query". So users would see the real latency. How about this?

**Comment by nagachika** [comment]
In fact, the encoding text embedding is not take place on the browser, but on the GCE instance and it is invoked from App Engine instance.
See https://github.com/groovenauts/MatchItFast/blob/master/doc/HOW_IT_WORKS.md#news-similarity-search for the data flow of the News Search.

I'm not sure but I think the additional latency of you experienced could  be the result of the spinning up of the App Engine instances.
I'd like to add the logging the latency for each text encoding and Matching Engine query for the time being.

**Comment by kazunori279** [comment]
When I tried it today, I didn't see the latency. Maybe the spinning up. Can you set the App Engine config to have a couple of instance up and running all the time, and also set it to get faster response with higher cost.

**Comment by nagachika** [comment]
I have set the `autoscaling.min_idle_instances` to 2 and add a warmup request handler.

**Comment by kazunori279** [comment]
Thanks!!
